
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2015 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
* Use of the Software is limited solely to applications:
*(a) running on a Xilinx device, or
*(b) that interact with a Xilinx device through a bus or interconnect.
*
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*XILINX CONSORTIUM BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
*Except as contained in this notice, the name of the Xilinx shall not be used
*in advertising or otherwise to promote the sale, use or other dealings in
*this Software without prior written authorization from Xilinx.
*

* 
* Description: FreeRTOS Configuration parameters
*
*******************************************************************/

#ifndef _FREERTOSCONFIG_H
#define _FREERTOSCONFIG_H


#define configUSE_PREEMPTION 1

#define configUSE_MUTEXES 1

#define configUSE_RECURSIVE_MUTEXES 1

#define configUSE_COUNTING_SEMAPHORES 1

#define configUSE_TIMERS 1

#define configUSE_IDLE_HOOK 0

#define configUSE_TICK_HOOK 0

#define configCPU_CLOCK_HZ ( 80000000UL )

#define configPERIPHERAL_CLOCK_HZ ( 80000000UL )

#define configUSE_MALLOC_FAILED_HOOK 1

#define configUSE_TRACE_FACILITY 0

#define configGENERATE_RUN_TIME_STATS 0

#define configUSE_STATS_FORMATTING_FUNCTIONS 1

//#define portCONFIGURE_TIMER_FOR_RUN_TIME_STATS configure_timer_stat

//#define portGET_RUN_TIME_COUNTER_VALUE getTickTraceCount

#define configTICK_TRACE_RATE_HZ ( ( portTickType ) (20000) )

#define configUSE_16_BIT_TICKS 0

#define configUSE_APPLICATION_TASK_TAG 0

#define configUSE_CO_ROUTINES 0

#define configTICK_RATE_HZ ( ( portTickType ) (200) )

#define configMAX_PRIORITIES 	5UL	//( ( unsigned portBASE_TYPE ) 4)

#define configMAX_CO_ROUTINE_PRIORITIES 2

#define configMINIMAL_STACK_SIZE ( ( unsigned short ) 120)

#define configISR_STACK_SIZE	( ( unsigned short ) 250 )

//#define configTOTAL_HEAP_SIZE ( ( size_t ) ( 28000 ) )

#define configMAX_TASK_NAME_LEN 20

#define configIDLE_SHOULD_YIELD 1

#define configTIMER_TASK_PRIORITY 1

#define configTIMER_QUEUE_LENGTH 10

#define configTIMER_TASK_STACK_DEPTH 120

#define INCLUDE_vTaskCleanUpResources 0

#define INCLUDE_vTaskDelay 1

#define INCLUDE_vTaskDelayUntil 1

#define INCLUDE_vTaskDelete 1

#define INCLUDE_uxTaskPriorityGet 1

#define INCLUDE_vTaskPrioritySet 1

#define INCLUDE_vTaskSuspend 1

#define INCLUDE_pcTaskGetTaskName 1


/* Prevent C specific syntax being included in assembly files. */
#ifndef __LANGUAGE_ASSEMBLY
	void vAssertCalled( const char *pcFileName, unsigned long ulLine );
	#define configASSERT( x ) if( ( x ) == 0 ) vAssertCalled( __FILE__, __LINE__ )
#endif


/* The priority at which the tick interrupt runs.  This should probably be
kept at 1. */
#define configKERNEL_INTERRUPT_PRIORITY			0x01

/* The maximum interrupt priority from which FreeRTOS.org API functions can
be called.  Only API functions that end in ...FromISR() can be used within
interrupts. */
#define configMAX_SYSCALL_INTERRUPT_PRIORITY	0x03

#endif
